# Mortuary Assemblage Diversity

The analysis of assemblage diversity is limited to Caddo mortuary contexts at the Mounds Plantation, George C. Davis, and Gahagan Mound sites where Gahagan bifaces were recovered.

```{r diversity, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
data <- read.csv("gahagan-diagnostics.csv")

library(vegan)
# assemblage size (N)
N <- rowSums(data[3:15])
N ## assemblage sizes range from:

# how many of each type were found?
T <- colSums(data[3:15])
T ## quantity of each type (T) found across contexts

# data by percentage
data.pct <- data[3:15]/N*100
## mean percent (Mp) of each type across assemblage
Mp <- colMeans(data.pct)
Mp

#diversity, richness
## richness (S) = number of types in assemblage
S <- specnumber(data[3:15])
S

## ubiquity (U) = number of assemblages that contain a particular type
U <- specnumber(data[3:15])
U

## percentage of sites that have each type
Up <- U/length(N)*100
Up

# Shannon diversity
H <- diversity(data[3:15])
## high diversity = more types and spread more evenly over types
H

# Simpson index
D1 <- diversity(data[3:15], 
                index = "simpson")
## probability that two artifacts drawn randomly represent different types
D1

# inverse Simpson index
D2 <- diversity(data[3:15], 
                index = "invsimpson")
## effective number of types
D2

## effective number of types for Shannon diversity index
Hmax <- exp(H)
Hmax

# evenness
## Pielou's J
J <- H/log(S)
## Shannon diversity index divided by natural log of richness
J

## ratio of effective species to richness
E <- Hmax/S
E
```

```{r diversity2, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap="Caddo burial assemblages that include Gahagan bifaces; 1, 41CE19-F134; 2, 41CE19-F119; 3, 16RR1-BP2; 4, 16RR1-BP3; 5, 16CD12-BP1; 6, 16CD12-BP2; 7, 16CD12-BP5; 8, 16CD12-BP8. The three sites in the lower part of the left quadrat exhibit lower diversity and evenness, and each represents the earliest context at each site to include a Gahagan biface. Those sites in the upper right quadrat have higher diversity and evenness, and occur later than those in the lower left quadrat."}
# summarize assemblage diversity to identify high & low diversity assemblages
library(maptools)
pch <- c(1, 3)[as.factor(data$region)]
plot(H, J, 
     pch = pch)
abline(h = median(J), 
       v = median(H), 
       lty = 2)
pointLabel(H, J, 
           rownames(data), 
           cex = .75)
leg.txt <- c(as.expression(bquote("Northern Behavioral Region")), 
             as.expression(bquote("Southern Behavioral Region")))
legend("bottomright", 
       leg.txt, 
       pch = c(1, 3))
```

```{r diversity3, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# sample size and richness
plot(S~N, 
     ylim = c(0, 12), 
     xlim = c(0, 184), 
     pch = 16)
abline(h = seq(0, 12, by = 2), 
       v = seq(0, 184, by = 50), 
       col = "black", 
       lty = 3)

# logarithmic function
data.log <- lm(S~log(N))
summary(data.log)
deviance(data.log)
xval <- seq(1, 184, by = 1)
lines(xval, 
      predict(data.log,
              data.frame(N = xval)),
      lty = 1)

# power function
data.pow <- lm(log(S)~log(N))
summary(data.pow)
sum((S-exp(fitted(data.pow)))^2)
lines(xval, 
      exp(predict(data.pow,
                  data.frame(N = xval))), 
      lty = 2)
```

```{r diversity4, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap="Rarefaction curve and confidence limits (dashed lines) for comparison of individual assemblages to the composite. Results demonstrate that diversity in the mortuary assemblages from 41CE19-F119 and 16RR1-BP3 are lower than expected based on the rarefaction curve."}
# rarefaction curve
## how do individual assemblages compare to the composite?
xval <- seq(2, 200, by = 2)
data.rar <- rarefy(T, xval, se = TRUE)
Est <- data.rar[1, ]
Sd <- data.rar[2, ]
rare <- cbind(lower = Est-2*Sd, 
              expected = Est, 
              upper = Est+2*Sd)

plot(S~N, 
     ylim = range(rare), 
     xlim = range(xval), 
     pch = 16)
matlines(xval, rare, 
         type = "l", 
         lty = c(2, 1, 2), 
         col = "black")
```
