project:
  type: website

website:
  margin-header: |
    ![](/images/slab.png)
  navbar:
    logo: "sfasu.png"
    right:
      - href: index.qmd
        text: Home
      - text: Temporal
        menu:
          - gahagan14c.qmd
          - seriate.qmd
      - text: Diversity
        menu: 
          - diversity.qmd
      - text: Geometric Morphometrics
        menu:
          - modelgeom.qmd
          - landprotocol.qmd
          - gm.qmd
          - gmdiv.qmd
          - gmevo.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
